baseURL = 'https://crocidb.com/'
languageCode = 'en-us'
title = "Bruno Croci"

theme = 'pixyll'
contentdir = "content"
publishdir = "public"
builddrafts = false
canonifyurls = true

[markup]
  [markup.goldmark]
      [markup.goldmark.renderer]
            unsafe = true

[indexes]
  category = "categories"
  tag = "tags"

[params]
  author = "Bruno Croci"
  authorWebsite = "https://bruno.croci.me/"
  description = "I write about programming, gamedev, hacking projects, creative code, photography and my thoughts about anything that I like."
  homeIntro = """Hi. I'm **Bruno Croci**, also known online as **crocidb**, programmer and hobbist artist based in DÃ¼sseldorf, Germany. I'm a tinkerer who loves to create stuff. My main interestest are *video games*, *music*, *photography* and *programming* in general. 

Go to [/about](/about) for more info, [/now](/now) for what I'm currently up to, or check [Things I've Made](/things-ive-made) for a list of projects."""
  news = "I'll be at FOSDEM 2026 in Brussels!"
  keywords = "programming, gamedev, hacking, coding, photography, thoughts"
  
  google_analytics_id = "G-E3L73E2DVK"
  twitter_username = "CrociDB"
  paginate = 10
  
